### ISSUE TITLE
present?を使い可読性をあげられないか検討する

### ISSUE THREAD

**Issue by norotime** [masarusan24/hanaguri-silver#12]
https://github.com/masarusan24/hanaguri-silver/blob/5f97bca4e6880891bcee82c3079ad33458e3a8ea/app/loyalties/games_loyalty.rb#L3

既にあるヘルパーメソッドは有効活用しましょう。
http://api.rubyonrails.org/classes/Object.html#method-i-present-3F

**Comment by masarusan24** [comment]
確かに `!user.nil?` より `user.present?` の方がわかりやすいので修正します。
