### ISSUE TITLE
CRUD全てに適用させる場合は、onlyはつけない

### ISSUE THREAD

**Issue by norotime** [masarusan24/hanaguri-silver#14]
https://github.com/masarusan24/hanaguri-silver/blob/5f97bca4e6880891bcee82c3079ad33458e3a8ea/app/controllers/games_controller.rb#L5

@ito-masato どうしても別名のアクションを使いたい場合などやむを得ない場合は、exceptを使いましょうか。

**Comment by masarusan24** [comment]
@norotime `index`, `show` アクションには適用させたくないのでこのような書き方になっております。
※試合一覧は未ログイン含めた全ユーザが見られるようにしたい。

```
before_action :authorize_action, except: %i[index show]
```

こうしておけば他のアクションが追加された時も `authorize_action` が効くと思うので、このようにします。

**Comment by norotime** [comment]
@masarusan24 はい。 :D
